version: 'version 1.0.0'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
        - wordpress
    env_file: .env
    volumes:
        - wordpress:/var/www/html
    restart: on-failure
    networks:
      - inception
    ports:
        - "443:443"

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file: .env
    volumes:
        - wordpress:/var/www/wordpress
    restart: on-failure
    networks:
      - inception
    expose:
      - 9000

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
    volumes:
        - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception
    expose:
        - 3306
  
  networks:
    inception:
      driver: bridge

  volumes:
    wordpress:
    mariadb: