version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
        - wordpress
    env_file: .env
    volumes:
        - wordpress:/var/www/html
    restart: always
    networks:
      - inception
    ports:
        - "443:443"

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file: .env
    volumes:
        - wordpress:/var/www/html
    restart: always
    networks:
      - inception
    expose:
      - 9000

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
    volumes:
        - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception
    expose:
        - 3306
  
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/rmarceau/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/rmarceau/data/mariadb
      o: bind
      type: none